//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASVE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public decimal CreditValue { get; set; }
        public decimal TotalCredits { get; set; }
        public System.Guid fk_Departmet { get; set; }
        public bool Active { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
